export enum ErrorCode {
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    INVALID_TOKEN = 'INVALID_TOKEN',
    EXPIRED_TOKEN = 'EXPIRED_TOKEN',
    MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
    INVALID_INPUT = 'INVALID_INPUT',
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    DATABASE_ERROR = 'DATABASE_ERROR',
    SERVER_ERROR = 'SERVER_ERROR',
}
