export enum NotifyWhen {
    IMMEDIATELY = 'IMMEDIATELY',
    FIVE_MINUTES = 'FIVE_MINUTES',
    TEN_MINUTES = 'TEN_MINUTES',
    FIFTEEN_MINUTES = 'FIFTEEN_MINUTES',
    THIRTY_MINUTES = 'THIRTY_MINUTES',
    ONE_HOUR = 'ONE_HOUR',
    TWO_HOURS = 'TWO_HOURS',
    ONE_DAY = 'ONE_DAY',
}
